# Generated by Django 6.0.1 on 2026-01-07 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
